[server]
host = ""
port = "3001"

[log]
log_dir = "./log"
log_std = "true"

[static]
upload_dir = "./upload"

[push]
api_key = "AAAAyQ2ofN0:APA91bEz66dHhehSpnQDpjolBt9EeU9o2ZOi_Tc5Z7slUfQ_CXGH9Ww6sx4cC8bBUgZl01gTXmcW5Cfo84ymLQqfkNi_0NL233MCVFfEDUKkgXPYIXYwdM6mtUvo3aOdGaCGcLSOaEk5"

[db]
host = "163.44.206.108:27017"
uname = "trunglen"
password = "trungyeulen4ever"
name = "wedding"